### ISSUE TITLE
Possible to merge exist abbyy xml with an image-only pdf?

### ISSUE THREAD

**Issue by shutingh** [ocrmypdf/OCRmyPDF#1002]
I already got abbyy ocr results (xml), and images, I'd like to merge them into a searchable pdf.
Does OCRmyPDF have this feature?
I've read about` ocrmypdf.hocrtransform` part, not sure if this can apply to abbyy xml.

**Comment by jbarlow83** [comment]
OCRmyPDF does not implement the [Abbyy XML format](https://support.abbyy.com/hc/en-us/articles/360017270080-Output-XML-document) and this format is quite different from [hOCR](http://kba.cloud/hocr-spec/1.2/).

Using the existing plugin interface you could create an "AbbyyOcrEngine" that translates the XML to hOCR, and then OCRmyPDF would perform hocrtransform. Or you could render directly to single page OCR PDFs and let OCRmyPDF combine and optimize.

Since most people who use Abbyy can use it to create PDFs directly, and Abbyy probably has a way of converting its XML format to PDF, I don't see a reason to add this feature to OCRmyPDF. But if it seems useful to you, it could be done with a plugin.

**Comment by shutingh** [comment]
> OCRmyPDF does not implement the [Abbyy XML format](https://support.abbyy.com/hc/en-us/articles/360017270080-Output-XML-document) and this format is quite different from [hOCR](http://kba.cloud/hocr-spec/1.2/).
> 
> Using the existing plugin interface you could create an "AbbyyOcrEngine" that translates the XML to hOCR, and then OCRmyPDF would perform hocrtransform. Or you could render directly to single page OCR PDFs and let OCRmyPDF combine and optimize.
> 
> Since most people who use Abbyy can use it to create PDFs directly, and Abbyy probably has a way of converting its XML format to PDF, I don't see a reason to add this feature to OCRmyPDF. But if it seems useful to you, it could be done with a plugin.

Thank you for your help.  I'll give it a try.
Or is there a way to transfer the text layer of a PDF to another PDF?

**Comment by jbarlow83** [comment]
You could use the "OcrGrafter" class in OCRmyPDF to transfer the text layer of an "OCR text only PDF" to another PDF.

The text layer is imaginary. I use the term because people understand it, and because OCRmyPDF does insert OCR in a PDF object that could be removed all at once. But there's unfortunately no standard way to insert OCR into a PDF, and thus, a mix of strategies are used, and it's not easy to distinguish OCR text from printable text.

**Comment by shutingh** [comment]
> You could use the "OcrGrafter" class in OCRmyPDF to transfer the text layer of an "OCR text only PDF" to another PDF.
> 
> The text layer is imaginary. I use the term because people understand it, and because OCRmyPDF does insert OCR in a PDF object that could be removed all at once. But there's unfortunately no standard way to insert OCR into a PDF, and thus, a mix of strategies are used, and it's not easy to distinguish OCR text from printable text.

So if the PDF is not text only, but a printable and searchable one, OCRmyPDF cannot separate the text info to merge into another pdf, right?

**Comment by jbarlow83** [comment]
Ghostscript has options to print a PDF while suppressing text, or vectors, or images (see their documentation for `-dFILTERTEXT` for example). I think you'd find it more suitable to the task of separating these elements of PDF. For more complex PDFs all bets are off in terms of whether these features will work as expected.
