### ISSUE TITLE
Docker image: Ship SIMD version of tesseract for better performance

### ISSUE THREAD

**Issue by jonashaag** [ocrmypdf/OCRmyPDF#1007]
It might be worthwhile to ship SIMD (SSE, AVX) versions of Tesseract with the Docker image. In my experiments I got 30-50% speedup over the Ubuntu tesseract binary with the following Dockerfile (Tesseract binary attached):

```dockerfile
FROM jbarlow83/ocrmypdf

COPY tesseract /usr/bin/tesseract

# Usage:
# docker build -t ocrmypdf-simd .
# docker run -e TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/ -i ocrmypdf-simd ...
```
[ocrmypdf-avx512.zip](https://github.com/ocrmypdf/OCRmyPDF/files/9410231/ocrmypdf-avx512.zip)

**Comment by jbarlow83** [comment]
```
> docker run --rm --entrypoint /usr/bin/tesseract jbarlow83/ocrmypdf  --version
tesseract 4.1.1
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
```

The binary embedded in the Docker image includes most of SIMD, just not AVX512.
I think the thing to do will be to switch to the Tesseract 5 PPA rather than using 4.1.1 as shipped by Ubuntu at the next major release of OCRmyPDF.

I don't know want to do that to the Docker image at the moment since it could be a breaking change. You could modify the existing image to update to Tesseract 5 using a new Dockerfile that does something like:

```
RUN apt-get update && apt-get install -y --no-install-recommends \
  software-properties-common
RUN add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
RUN apt-get upgrade
```

(Note: did not examine the zip file.)

**Comment by jonashaag** [comment]
Whoops, I should have checked `tesseract --version` before claiming that the Ubuntu one misses SIMD, sorry. In fact it seems that the only difference is 4.x vs 5.x (my CPU doesn't support AVX512). Will try your PPA instructions.
