### ISSUE TITLE
Disable metadata fixup in order to stay at PDF version 1.4?

### ISSUE THREAD

**Issue by cproof** [ocrmypdf/OCRmyPDF#1012]
I'm using ocrmypdf in a project where compatibility with PDF version 1.4 is required.

After some debugging, I found that I can retain the input version until the PDF was grafted:

```bash
> ocrmypdf -l deu --force-ocr input.pdf --output-type pdf --pdf-renderer hocrdebug -v 2 -k --optimize 0

  DEBUG ocrmypdf - ocrmypdf 13.4.0+dfsg
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 4.1.1
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.55.0
  DEBUG ocrmypdf.helpers - os.symlink(input.pdf, /tmp/ocrmypdf.io.wosz_ws8/origin)
```

```bash
> pdfinfo origin.pdf
Producer:        WeasyPrint 56.1
Optimized:       no
PDF version:     1.4

> pdfinfo graft_layers.pdf
Producer:        WeasyPrint 56.1
Optimized:       no
PDF version:     1.4
```

However, the "metafix" version is then converted to 1.5:
```bash
>  pdfinfo metafix.pdf
Creator:         ocrmypdf 13.4.0+dfsg / Tesseract OCR 4.1.1
Producer:        pikepdf 5.0.1+dfsg
Optimized:       no
PDF version:     1.5
```

```bash
> pdfinfo optimize.pdf
Creator:         ocrmypdf 13.4.0+dfsg / Tesseract OCR 4.1.1
Producer:        pikepdf 5.0.1+dfsg
Optimized:       no
PDF version:     1.5
```

Is there a possibility to disable this "fixing" of metadata? I'm using Ubuntu 22.04.1 and the packages provided there.

**Comment by jbarlow83** [comment]
Default behavior is to save with object streams generated which reduces the size of the PDF for no real penalty.

In addition to that ghostscript, pikepdf and/or ocrmypdf might increase the PDF version if they notice the version is incorrect, i.e. it uses a feature introduced in a higher version.

Since PDF 1.4 and 1.5 are both about 20 years old so compatibility is usually not an issue.

You could fork ocrmypdf and customize ocrmypdf._pipeline.get_pdf_save_settings to disable for your requirements, or create a custom plugin (replacing the default optimizer, say) and use pikepdf.Pdf.save(..., force_version='1.4') to force an earlier version.

Because this can be implemented with a plugin, I don't see a case for adding this feature to the core program.

**Comment by cproof** [comment]
Thanks for the respones! I'll look into that.
