### ISSUE TITLE
output JSON format

### ISSUE THREAD

**Issue by emresaracoglu** [ocrmypdf/OCRmyPDF#1056]
Hello,

Is it possible to get the console output as JSON?
Thank you

**Comment by jbarlow83** [comment]
If you run ocrmypdf in a script, instead of installing its default logger, you could install a custom logger that formats output as JSON.

Demo here - this sets up the standard logger.
https://ocrmypdf.readthedocs.io/en/latest/batch.html#id1

ocrmypdf's log messages are not highly normalized. They don't have always contextual information, and they should not be considered a stable ABI (if there are typos in log messages for example, they will get fixed in minor releases). To make ocrmypdf's logging better it would need to move to something like structlog or something that decouples the "view" from the model-controller that does the work. These changes would be a ways down the road but if you're interested I may be able to support PRs along those lines.
