### ISSUE TITLE
Program doesn't recognize white text on gray background

### ISSUE THREAD

**Issue by Antiwhore** [ocrmypdf/OCRmyPDF#1061]
**Describe the bug**
I've tried to recognize an issue of a magazine. It has a rich formatting where text frequently changes its position, color, font and shape. I don't expect the program to recognize heavily skewed text (there is some), but I wanted it to recognize straight text in simple fonts in whatever color. And this is what it didn't do. There are blocks in the file which have white text on gray background. They are perfectly recognizeable by me, but turned out to be too much for the program - it didn't provide any text for those blocks at all.

**To Reproduce**
Run the program on the attached file with no additional options.

**Example file**
[input.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/10435299/input.pdf)

**Expected behavior**
I want all text to be recognized. I didn't find a proper option for this in the manual. Maybe it's a one of Tesseract itself.

**Screenshots**
The place with no recognized text
![Screenshot_20230117_161501](https://user-images.githubusercontent.com/121800962/212908865-46a81f6a-01b7-4847-9ff2-2c174c9c29ab.png)

**System**
 - OS: Linux
 - OCRmyPDF Version: 10.3.1+dfsg
 - How did you install ocrmypdf: package manager

**Comment by jbarlow83** [comment]
Try the `--tesseract-thresholding` argument. Requires Tesseract 5.

ocrmypdf 10.3.1 is quite old - you may need to use a newer version to get this argument.

**Comment by Antiwhore** [comment]
I updated both Tesseract and the program and used this option - it doesn't help. I wanted to read about it in the man and there turned out to be no man! And it's not available in your pip repository either. Where are the docs?

**Comment by jbarlow83** [comment]
This is a volunteer-run project and the result of thousands of hours of my personal effort over many years and hundreds from others. You are asking for free support in a tone that is rather demanding, as if I were working for you and not performing to our contractual obligations. I am saying this to remind you of the nature of this free software. We all want software to be better and we are all frustrated when it does not perform to our expectations, but there is only so much time. Also, please understand that it is ultimately a problem in the Tesseract OCR engine that it struggles with low contrast images of this sort, rather than a technical deficiency in OCRmyPDF itself.

There is help available in `ocrmypdf --help` including documentation for this parameter. You can use `help2man` to generate a man page. The main documentation is linked on the project's front page on GitHub; sadly it is missing information this feature, although the --help text adequately describes it use. You are welcome to contribute documentation if you have the time (I currently don't). The documentation also describes how one can generate the intermediate temporary files, allowing one to examine what the OCR engine "sees", which can help with tuning parameters.

**Comment by Antiwhore** [comment]
"in a tone that is rather demanding". My friend, I was asking you a question, not demanding anything. If you consider innocent questions as accusations or demands, you have a mental problem not related to software. Actually it's a sign that you're not sure of your own product. Cause if you were, you wouldn't have to defend yourself.
As for the software side, I'd like to remind you something. FREE SOFTWARE IS NOT JUNK SOFTWARE. And it was never meant to be. And the fact that you're not paid for it doesn't release you from responsibility for its quality. And if you, as you said, volunteered to develop this tool, keep this principle in mind. Also remember that nobody's going to make bows to you simply for the fact that you are doing this - the software must solve its problem, only then you gain the credit for this work.
And finally, I managed to recognize that document properly in gImageReader with the same tesseract package. Its interface doesn't allow me to see the options it uses, but when I run it through that page, almost all symbols in that area are recognized successfully. That program has other major problems, but the recognition works properly. So tesseract itself is capable of it.
