### ISSUE TITLE
Feature Request: GPU OCR pipeline e.g. via EasyOCR

### ISSUE THREAD

**Issue by systemofapwne** [ocrmypdf/OCRmyPDF#1071]
**Request**
Adding a pipeline for speeding up OCR via GPU processing is highly beneficial.

**Possible solution**
Tesseract so far is very great but mostly is bound to CPU processing only. 
It however supports OpenCL here and there but that is still W.I.P. and so far is reported to not be significantly faster than on the CPU. This might change at some point but so far, tesseract seeems to not to be a good candidate for GPU OCR procesing.

On the other side, EasyOCR does utilize the GPU and is extremely fast for OCR. So far, it seems to accept images and returns bare lists of OCRed text. So a wrapper has to be implemented in order to create HORC or OCRed PDF files, "sidecar" files etc.
That however might all be possible with OCRMyPDFs' plugin engine I guess.

**Comment by isspid** [comment]
I would also be interested in this. I have found EasyOCR to perform better than tesseract for my use case, but the fact that they don't produce PDF files is a pity.

**Comment by jbarlow83** [comment]
EasyOCR is now in progress. It mostly works as proof of concept but there's still more to do to.

It will likely be delivered as an optional plugin since CUDA dependencies are fussy.

**Comment by jbarlow83** [comment]
@gardner @isspid @systemofapwne 
Here you go: https://github.com/ocrmypdf/OCRmyPDF-EasyOCR

As mentioned, it's a plugin for the moment and will likely stay that way. It could be bundled with ocrmypdf as a "built-in plugin" if it becomes quite mature, essential and not a burden for downstream packagers (Debian, in particular, will not have the easiest time since CUDA is nonfree).

Collaborations are very welcome!

It may be a better to implement something similar to the GlyphlessFont in Tesseract's PDF renderer, although that will likely introducing the wordswithoutspacesissue.

Note that I will probably replace my custom ocrmypdf/executor with the anyio library, since I believe this does everything we need and would provide more granular parallelism; and I will replace with argparse and tqdm with rich and typer.
