### ISSUE TITLE
ocrmypdf generating white patch in output pdf?

### ISSUE THREAD

**Issue by gogineniravikumar** [ocrmypdf/OCRmyPDF#1084]
When I ran ocrmy pdf on this file the generated pdf have a white patch. This is happening only when I use "clean_final" option.  

ocrmypdf.ocr('page.pdf', 'output.pdf', clean_final=True)

The white patch issue should not be happen in generated pdf.

![image](https://user-images.githubusercontent.com/50137469/226818497-5658646c-07f5-4734-b0a7-58b8f70ae9de.png)

**System (please complete the following information):**
 - OS: windows, linux
 - Python version: all versions, I am using python 3.8
 - OCRmyPDF version: latest
 - Platform: x64 

How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip? 
using pip in environment
python3 -m pip install ocrmypdf

it's happening all the time.
file link
https://drive.google.com/file/d/1TaPpl_qE45E9bOK0jJ-QLFxY5ZVmtKXy/view?usp=sharing

**Comment by jbarlow83** [comment]
ocrmypdf uses a program called unpaper clean images. Unpaper is designed mainly to clean up files with noisy backgrounds from poor quality scans -- it will not work well on images like yours. When --clean is used, ocrmypdf cleans a special version of the image that is sent for OCR, allowing better OCR results on bad scans (while occasionally removing desired content). The output --clean-final should be inspected because unpaper may remove desired content, as in this case, assuming the yellow mark indicates desired content being removed.

I'll close the issue because this is not a supported usage (and we cannot change unpaper).
