### ISSUE TITLE
Use Github Releases for notifications

### ISSUE THREAD

**Issue by fabiante** [ocrmypdf/OCRmyPDF#1085]
Hi there!

I'd like to stay in touch with this project and get notifications whenever a new release is being made. It seems that the project uses git tags for tagging specific versions (nice) but does not create github releases. Would that be an additional hassle to do?

I have subscribed to Release notifications in this repo but AFAIK that does not notify me if the project uses only git tags.

Sincerely!

**Comment by jbarlow83** [comment]
It looks like there's a good tool now to trigger releases. Historically it was a separate step which made things annoying.

Note to self:
https://github.com/marketplace/actions/automatic-releases

**Comment by FabianTe** [comment]
Nice idea. [I tried to test that action in my fork](https://github.com/FabianTe/OCRmyPDF/actions/workflows/release.yml).
Seems to do the trick, but don't forget to configure the Github Action permissions appropriately, as this commenter statet: https://github.com/actions/first-interaction/issues/10#issuecomment-1475121828

Otherwise the action fails.
