### ISSUE TITLE
Feature Request: Provide for downloading of language models

### ISSUE THREAD

**Issue by simsong** [ocrmypdf/OCRmyPDF#1094]
**Is your feature request related to a problem? Please describe.**
Performance is greatly improved when language models are present, but language files are not installed by default.

**Describe the solution you'd like**
It would be useful if there was a provision for downloading language files for specified languages and then storing the language file in a specified location.

**Describe alternatives you've considered**
- [ ] Decide on a specific location (for example, a dot directory in the user's home directory)
- [ ] Provide a command-line switch to download all or specified language files.

**Example file**
Language files appear to be here:
* https://github.com/tesseract-ocr/tessdata

**Additional context**

**Comment by jbarlow83** [comment]
Unfortunately this is not something ocrmypdf can do in a portable way, because language files are normally managed by the system package manager and should be installed in that way. I will change the error message to give more details about how to do this and point people to the documentation.

(Which is here:
https://ocrmypdf.readthedocs.io/en/latest/languages.html )
