### ISSUE TITLE
Replace text from original PDF with OCR'd Text

### ISSUE THREAD

**Issue by FrancisBaileyH** [ocrmypdf/OCRmyPDF#1100]
**Is your feature request related to a problem? Please describe.**
I'm scanning a large set of old documents in varying states. Often times the pages/text are skewed due to warped pages, bends, etc. When viewers are opening the document it can be a bit jarring to read the warped text.

**Describe the solution you'd like**
I'd like to overlay the OCR'd text on top of/in replacement of the original skewed text. The reason for that is the OCR'd text is output behind the skewed text but in a straight horizontal line and in the correct position on the page. One challenge I see is that the text overlay will need a background to mask/cover the original text. For my purposes even a blank white bar would suffice. With later iterations, a background colour detection or blending mechanism could be used.

**Describe alternatives you've considered**
I have only considered ocrmypdf for these purposes as that's the main software I'm using to enrich my scans.

**Comment by jbarlow83** [comment]
The generated OCR text is an interpretation of the image. Because OCR engines improve with time, removing the original image is never a good idea - a future OCR engine will do a better job of extracting text from difficult inputs. Removing the original image makes any OCR errors permanent and irreversible.
