### ISSUE TITLE
[Feature]: Parameter to automatically remove blank pages

### ISSUE THREAD

**Issue by GrabbenD** [ocrmypdf/OCRmyPDF#1121]
# Issue
A lot of printers are able to scan multi-page documents while excluding blank pages. However, this feature usually tends to include blank pages anyway, especially when using HP printers.

# Request
From my understanding this project is already able to detect blank pages judging by `[tesseract] Empty page!!` message!
The ability to automatically remove blank pages from the PDF document through a CLI parameter would be extremely useful 🙂 

(P.S.: I wasn't able to use Feature request format as it gives me a 404 after submitting)

**Comment by jbarlow83** [comment]
We don't show Tesseract the same image that the user sees, for various reasons, so it may think a page is empty, but only because of how we've processed it - so that information alone is not enough to exclude a page.

Generally speaking - blank page detection is a general AI problem. In some contexts a scribbled handwritten note on the back of a page could very important, or say, an underexposed black and white photo, and existing methods are not good enough to distinguish from noise from meaningful content. The expectations are also different for archivists (who want to preserve everything) and "optimizers" (who want the smallest files). When I doubt, I lean towards the archivists, because keeping extra data around is almost always safer than deleting something useless. ocrmypdf is designed to be safe to use on thousands of files without having to individually review its decisions - I have yet to see a blank page detection algorithm I would be confident in, despite how deceptively simple the problem seems.

**Comment by jbarlow83** [comment]
Closing because no existing method is safe enough, to the best of my knowledge. Happy to review any research papers if someone has any.
