### ISSUE TITLE
does ocrmypdf create an invisible text layer?

### ISSUE THREAD

**Issue by lbr991** [ocrmypdf/OCRmyPDF#1123]
How does ocrmypdf embed the text layer in the original pdf?
Does it create an invisible text layer and if yes, what library does it use?

**Comment by amitdo** [comment]
>does ocrmypdf create an invisible text layer?

Yes.

 >what library does it use

(lib)tesseract.

**Comment by lbr991** [comment]
Thanks, can you share where in the source code it does this? 
Also, is there a way to use another ocr engine (Textract, Google Vision etc.) to extract the chars and then use libtesseract to create the invisible text layer?

**Comment by lbr991** [comment]
Also, was ocrmypdf using ghostscript or pymupdf (or both?) for this in the past?

**Comment by jbarlow83** [comment]
OCRmyPDF has a plugin interface that lets you provide an alternative OCR engine. I am working on a demo of this using EasyOCR in combination with something like the existing reportlab hOCR renderer in src/hocrtransform.py to create the text layer. libtesseract cannot create an invisible text layer except from Tesseract-generated OCR.

OCRmyPDF uses Tesseract in subprocesses because historically tesseract was a lot less stable and using libtesseract in Python process tended to crash too often. That's no longer the case but the design decision remains anyway.

**Comment by jbarlow83** [comment]
OCRmyPDF uses Ghostscript currently, to rasterize PDF pages to images before OCR. 

I explored the use of PyMuPDF many versions ago but dropped it due to its restrictive AGPL licensing and unusual static lib packaging that would have meant ocrmypdf would have to be removed from Linux package managers.

**Comment by lbr991** [comment]
So ocrmypdf uses libtesseract by default to create the invisible layer but also contains code that uses reportlab for this in case that another OCR engine is selected, did I get this correctly? 

Ghostscript is also AGPL, no?

**Comment by jbarlow83** [comment]
>ocrmypdf uses libtesseract by default to create the invisible layer but also contains code that uses reportlab for this in case that another OCR engine is selected, did I get this correctly?

It has two PDF renderers, as it calls them. Early on, Tesseract would output hOCR, not PDF at all, so it would convert to PDF. Tesseract then added a PDF tenderer of its own, which ocrmypdf can use too. Tesseract's PDF supports non Latin alphabet better but has problems with word segmentation in some PDF viewers. (Ithasalongstandingissueofrunningwordstogether.)

**Comment by jbarlow83** [comment]
Ghostscript is AGPL but calling it as a subprocess is generally accepted as a "low linkage interface". I advise people to be mindful of possible AGPL obligations if attempting to deploy a web service using ocrmypdf and thus Ghostscript. Generally this situation of using AGPL binary does not trigger distribution requirements unless one has modified Ghostscript; see discussion here. https://opensource.stackexchange.com/questions/650/do-i-have-to-offer-the-source-of-an-agpl-v3-0-licensed-web-app-even-if-i-didn

**Comment by amitdo** [comment]
@[jbarlow83,

AGPL is considered very risky by many companies. Some companies like Google disallow their employees to use any AGPL software.

Can `pdfimages` be used as replacement for Ghostcript? Did you ever consider using it in OCRmyPDF ?

 `pdfimages` is a CLI tool, part of Poppler/Xpdf, licensed under GPLv2/GPLv3.

**Comment by jbarlow83** [comment]
Ghostscript is currently used for:
* PDF to image conversion
* PDF to PDF/A conversion

`pdftoppm` or `pdftocairo` could be used instead of Ghostscript for PDF to image, and the plugin interface allows replacement of both functions for which Ghostscript is used. Anyone who is concerned about the use of Ghostscript could write a plugin to use pdftocairo instead.

There is no open source software that can accurately convert PDF to PDF/A when the input PDF is not trivial. Maybe Pdfbox can do it, but that is Java only. iText probably can too, but that's also AGPL or commercial. This is not a mandatory feature of OCRmyPDF but it is a default, and PDF/A output has been a feature since the earliest release.

I have had brief contact with Artifex's licensing group. While I cannot speak for them, they know about OCRmyPDF and do not consider it AGPL-infringing. Note that re: their licensing page, OCRmyPDF does not distribute Ghostscript (one must obtain a copy elsewhere, such as through the system package manager), OCRmyPDF uses the command line interface of Ghostscript so it no way forms a single executable, and OCRmyPDF is designed in such a way that would allow one to replace Ghostscript. OCRmyPDF's documentation covers some of these concerns.
