### ISSUE TITLE
[Feature]: Remove images of text recognized

### ISSUE THREAD

**Issue by Kimi-Arthur** [ocrmypdf/OCRmyPDF#1126]
### Describe the proposed feature

For example, if I have a low quality pdf, I may want to use rendered text (text + font), instead of the original image.

Other areas may need to be kept as is.

**Comment by jbarlow83** [comment]
If OCR misdetects text it will make the original text unrecoverable, and prevents use of OCR in the future to fix the problem. 

I know some PDF editors offer this but I don't think it's a good idea in principle because of the possibility of irreversible data loss. 

Adobe has something called ClearScan which constructs a custom font and images to capture the residual images not covered by the font. The residual images work to ensure nuances are not lost. This would be quite complicated to replicate.
