### ISSUE TITLE
[Bug]: When image quality is low or for skewed pdf's Ocrmypdf is not Ocring proper text. Missing some paragraphs. 

### ISSUE THREAD

**Issue by goginenir6** [ocrmypdf/OCRmyPDF#1130]
### What were you trying to do?

I ran ocrmypdf on this [file](https://drive.google.com/file/d/1_yCNkBjU16SCtd8jrresUpgoiJTtv8nM/view?usp=sharing) , The output pdf is not really good. I know if image quality is not good or for some of skewed scanned pdf's it's really hard to generate OCR text. 

But my question here is is there a way to insert text programmatically based on position.  Assume I know the position coordinates where I have to insert text in scanned pdf's. The manual user entered text I wanted to insert , The ocr un detected places. 

To achieve this functionality what classes should I override? How can I do it?

I am using **Hocrfile true, auto delete false** option to see the files. I observed that if I add any extra spans in HOCR file its creating text in output pdf. But I want help here to what classes should I override? And How could I achieve this. 

I hope this reply can help lot of blind people who can access pdf's.  Thanks in advance. 
 
 

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.)

### What operating system are you working on?

Linux

### Relevant log output

```plain text
ocred pdf generated with missed text.
```

**Comment by jbarlow83** [comment]
The image quality is too low for good results. Generally speaking, "OCR results are poor" is not something I can fix, because it's mostly up to the OCR engine. (You could try the new EasyOCR plugin: https://github.com/ocrmypdf/OCRmyPDF-EasyOCR )

You can insert text programmatically by editing the hocr file and manually combining.

OCRmyPDF is designed to do the best job it can without asking for user intervention beyond the command line, so that it can process thousands of files.

If you want a supervised OCR solution (that lets you fixed all of the mistakes and construct a "perfect" document) Abbyy FineReader can do that. Foxit PDF Editor would work too. It takes 15-30 minutes per page to fix everything, but that's the sort of tool one should use to correct all recognition mistakes.

**Comment by goginenir6** [comment]
Thanks for reply,

Can this "EasyOCR" may I use with HOCR renderer flow? 
if yes , Can you help me with some snippets or commands?
Thanks

**Comment by jbarlow83** [comment]
Error message - guessing one of setuptools or pip is out of date.

EasyOCR does not use the HOCR renderer. It works similar to the Tesseract PDF renderer. (HOCR does not support non-Latin fonts.)
