### ISSUE TITLE
[Bug]: PDF expands to 1.5G from 14M

### ISSUE THREAD

**Issue by alephpiece** [ocrmypdf/OCRmyPDF#1169]
### Describe the bug

I was working on turning some scanned Chinese books to searchable PDFs. Everything works perfectly except for one document expanding to 111x size after OCR. Any idea what happened? What should I do to reduce its size?

The output PDF:
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/22237751/69b5a2d1-80ec-4cd1-9599-e0fd706c7006)

### Steps to reproduce

```plain text
1. Run the code block

ocrmypdf -l chi_sim+chi_tra \
        --output-type pdf \
        --rotate-pages \
        --deskew \
        --clean \
        --skip-text \
        "王力文集·第9卷（汉语史稿）.pdf" output.pdf

2. Check the size of output.pdf
```

### Files

[王力文集·第9卷（汉语史稿）.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12929300/9.pdf)

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

15.2.0

### Relevant log output

```plain text
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 836/836 0:00:00
Postprocessing...                                                                               _sync.py:314
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization did not improve the file - optimizations will not be used                 optimize.py:711
Image optimization ratio: 1.00 savings: -0.0%                                              _pipeline.py:1019
Total file size ratio: 0.01 savings: -11028.4%                                             _pipeline.py:1022
The output file size is 111.28× larger than the input file.                               _validation.py:351
Possible reasons for this include:
--deskew was issued, causing transcoding.
```

**Comment by jbarlow83** [comment]
Each page of the PDF (after the first few) works like this:
- define an RGB colorspace
- using vector graphics, draw a filled black rectangle covering the whole page in that colorspace
- use a stencil mask to selectively hide/expose portions of that black rectangle

From OCRmyPDF's perspective, the use of the RGB colorspace means that each page needs to be promoted to RGB. The fact that the rectangle works out to black is a specific property of the colorspace (we can't assume black is 0 0 0 for any arbitrary colorspace). When any of ``--deskew --clean`` etc are issued, it forces promotion to full RGB.

Short term solution is to drop `--deskew --clean`. The file is fairly clean anyway.

(OCRmyPDF's optimizer throws an exception for `-O2` and `-O3` on this file due to some pikepdf issue, and then catches it and ignores the offending image. This is a fixable issue that needs to be addressed and would allow higher optimization settings.)

**Comment by jbarlow83** [comment]
no further information
