### ISSUE TITLE
[Feature]: More details for exception ColorConversionNeededError

### ISSUE THREAD

**Issue by noseshimself** [ocrmypdf/OCRmyPDF#1200]
### Describe the proposed feature

I'm getting this exception for a file that *should* be the same (all PDF invoices from the same source using the same background made with AI) as a number of other files from that source. ImageMagick's inspect does not show anything too strange about it.

Would it be possible to have the exceptions provide a bit more technical detail regarding the problem (in this case the color space parameters it found and what was wrong about them?

**Comment by jbarlow83** [comment]
Run `qpdf --json your file.pdf` and check, or post the results here. That will provide technical information without disclosing the file contents.

**Comment by jbarlow83** [comment]
See #1187. Especially [this comment](https://github.com/ocrmypdf/OCRmyPDF/issues/1187#issuecomment-1804924680).

The behavior described in the comment is now implemented: if a specific warning message is issued by Ghostscript, we exit with an error message, because it's known to produce bad PDF output. 

It's possible this is a bug or perhaps they consider the warning sufficient.

The warning message from Ghostscript is
```
Attempting to write a DeviceN space with an inappropriate alternate,
have you set ColorConversionStrategy ?
```
OCRmyPDF uses LeaveColorUnchanged by default, and Ghostscript is saying that there is an image with a color space that cannot be left unchanged. We simply parse for that warning and convert it to an error.

DeviceN is normally only used in offset printing - I'm not aware of scanners using it, but perhaps they do. Or maybe they are creating some sort of optimized custom color space. If you need more details about why a color space can't be converted you'd need to talk to Artifex.

**Comment by noseshimself** [comment]
> The behavior described in the comment is now implemented: if a specific warning message is issued by Ghostscript, we exit with an error message, because it's known to produce bad PDF output.

At least in one case the excellent graphic designer who prepared the (PDF background) letterhead actually created an incredible mess that was somehow working because the Adobe Reader most of the clients seemed to be using got something visible out of it but which was crashing my poor ChromeOS viewer. No Ghostscript involved, the moron was sitting in front of the computer when he created it.

**Comment by jbarlow83** [comment]
OCRmyPDF uses Ghostscript to perform PDF/A conversion.

**Comment by noseshimself** [comment]
Ok, I'm changing the workflow automation and doing that extraction in parallel to the OCR pipeline.

Thank you for the explanation!
