### ISSUE TITLE
[Feature]: Not to save images and opaque text

### ISSUE THREAD

**Issue by edwvee** [ocrmypdf/OCRmyPDF#1203]
### Describe the proposed feature

Is it possible to have as output a pdf without images, just opaque recognized text with preserved position?

**Comment by jbarlow83** [comment]
See here for the description of temporary files OCRmyPDF generates.
https://ocrmypdf.readthedocs.io/en/latest/advanced.html#debugging-the-intermediate-files
You can gather all of the _ocr_tess.pdf files, which under normal settings, will present as blank pages containing only the text, in the positions the text should appear. PDF viewers will allow you to copy the text out, and layout programs like Poppler `pdftotext -layout` will create a representation of the relative position all text in a monospaced font. You could use a tool like qpdf to merge these files together.

Using `--output-type hocr` and version <16, you would get visible text for Latin alphabet languages; as of v16 the ability to render visible text in this way will disappear. There is no way to get visible text for all languages, and it's unlikely to happen any time soon, because multilingual font rendering is very complicated.
