### ISSUE TITLE
[Bug]: complete letter salad

### ISSUE THREAD

**Issue by knabed** [ocrmypdf/OCRmyPDF#1209]
### What were you trying to do?

the complete OCR-layer is messed up. when I mark a line with the mouse for example the selection doesn't match the picture of the scanned text. when I copy&paste it into a text editor it doesn't make any sense it's just letter salad
image v15.4.4 works fine but afterwards the problem occurred 
I'm using docker on a Synology NAS

### Where are you installing from?

Docker container

### What operating system are you working on?

Linux

### Relevant log output

```plain text
➜ OCRmyPDF-LOG:
                  The installed version of Ghostscript 9.55.0, contains a remote code execution security vulnerability. Please upgrade to a newer version. For details see CVE-2023-43115. The issue is not known to affect OCRmyPDF or processing PDFs with Ghostscript, but upgrading Ghostscript is recommended.
                  reading file from standard input
                  
                  Start processing 3 pages concurrently
                      3 page is facing ⇧, confidence 10.92 - no change
                      2 page is facing ⇧, confidence 11.67 - no change
                      1 page is facing ⇧, confidence 10.30 - no change
                  
                  Postprocessing...
                  
                  
                  
                  Image optimization ratio: 1.19 savings: 16.1%
                  Total file size ratio: 0.80 savings: -24.9%
                  Output sent to stdout
                ← OCRmyPDF-LOG-END
```

**Comment by jbarlow83** [comment]
I have determined that this issue concerns a specific PDF file and I will need that file to test it, along with the command line or API you were using and other information in the issue template. 

If the file contains private information, here are some options:

- You can [encrypt the file with my public key](https://github.com/ocrmypdf/OCRmyPDF/wiki) as described here, to ensure that only @jbarlow83 can open it.
- You can attempt to produce a non-private file that likely has a similar issue. For example, if the PDF that caused the problem was created with a specific scanner software, perhaps that software is the problem. Scan some other document or a redacted document with the same equipment and software. (If you are not sure what to scan, print a page from Wikipedia.)
- You could try using Acrobat's Redact tools, or similar tools in other PDF editors, to remove personal information. Note that this will change the PDF and might fix the issue.
- You could run `qpdf --json yourfile.pdf > yourfile.pdf.json` and upload the resulting .json file here. That contains a structural description of the contents of the PDF. In most cases, this will not help; but occasionally it does.

If you cannot share the file, you could try the following workarounds to produce a visually similar PDF and find a way to OCR the file

- Refrying the PDF using Ghostscript `gs -q -sDEVICE=pdfwrite -o out.pdf in.pdf`.
- Printing the file to a "Print to PDF" virtual printer, which will reconstruct the PDF and perhaps create a new PDF without the issue.
- Using `ocrmypdf --force-ocr` which is more aggressive about removing document contents.

For now, I will close the issue. You are welcome to reopen it with a test file.

**Comment by knabed** [comment]
I scan the documents with my Brother MFC-L8690CDW and it worked until v15.4.4
I ran "ocrmypdf -frd -l deu+eng" with latest image on the file attached 
This problem applies on every scan since I used images after v15.4.4
[20231220_180411_printer_002441.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/13730206/20231220_180411_printer_002441.pdf)
