### ISSUE TITLE
[Bug]: OCRmyPDF does not preserve existing XMP metadata

### ISSUE THREAD

**Issue by jkorinth** [ocrmypdf/OCRmyPDF#1213]
### What were you trying to do?

Paperless-ngx user here: Noticed that custom XMP metadata is missing from all my pdf documents and seems to have been replaced by OCRmyPDF-generated XMP. In particular, I was using the Dublin Core elements `dc:contributor` and `dc:created`. I think all metadata not overwritten by OCRmyPDF should be preserved, if possible, and/or generate a warning if not.

### Where are you installing from?

Docker container

### What operating system are you working on?

Linux

**Comment by jbarlow83** [comment]
Preserving metadata is already implemented and has been working well for years, so this is likely some edge case of how XMP is handled at some point.

Please re-submit this as a "Problem with specific file" and all of the details requested there, especially the command line that paperless-ngx used to run ocrmypdf, which should be in its logs, and an example file. Include the before and after PDF, since it may be related to how XMP metadata is formatted. (For example, the metadata is still preserved, but some other system e.g. paperless-ngx cannot read the produced XMP metadata.)
