### ISSUE TITLE
[Bug]: RHEL 9 requires ghostscript 9.54 to work

### ISSUE THREAD

**Issue by nisbet-hubbard** [ocrmypdf/OCRmyPDF#1225]
### What were you trying to do?

Although RHEL backports things to its `gs` binary, the version is frozen at 9.54. Which means to use the latest ocrmypdf, one has to get a snap-distributed later `gs`. But this introduces permissions issues as shown in the log, and because `gs` options aren’t exposed, there’s no way to get round this.

Currently, we can only get your great ocrmypdf to work on RHEL 9 (the latest) by using v14.4.

Would it be possible by any chance to lower ocrmypdf‘s `gs` dependency to 9.54 so projects running enterprise linux can benefit from the newest version?

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.)

### What operating system are you working on?

Linux

### Relevant log output

```plain text
Start processing 2 pages concurrently                                                                              ocr.py:98
    1 Error: /undefinedfilename in (/tmp/ocrmypdf.io.9d25egvn/origin.pdf)                                 ghostscript.py:139
Operand stack:                                                                                                              
Execution stack:   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2                       
%stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push                             
Dictionary stack:   --dict:751/1123(ro)(G)--   --dict:0/20(G)--   --dict:85/200(L)--                                        
Current allocation mode is local                                                                                            
Last OS error: No such file or directoryGPL Ghostscript 10.02.1: Unrecoverable error, exit code 1
```

**Comment by jbarlow83** [comment]
For ocrmypdf 15, I decided to make Ubuntu 22.04 the baseline system mainly because that is what GitHub's CI provides. This is where the ghostscript 9.55 requirement comes from. It's very likely 9.54 would work well for most users - I'm not aware of any technical reason why it wouldn't.

It would be best to confirm RHEL9 has backported the fix for CVE-2023-43115 to Ghostscript 9.54. The patch looks trivial so this has probably been done already. I'd appreciate check this and also confirm that ocrmypdf's test suite passes on your RHEL9 environment when the ghostscript version check in `src/ocrmypdf/builtin_plugins/ghostscript.py` line 57 patched to 9.54 instead.

Assuming the above are both true, I can modify the minimum ghostscript version to 9.54 and introduce a maintainer-friendly variable to silence the Ghostscript CVE warning message. Then you'll have a native install with a one-line patch to suppress the warning, without the complications of snap.

---

If we want to go the snap route, the issue is that the Ghostscript snap and ocrmypdf need access to a common TMPDIR. If this were Docker we'd bind-mount ocrmypdf's /tmp/ocrmypdf.io.whatever folder to the container with `-v {ocrmypdf_tmp}:/tmp`. Not sure how to achieve the same with snap, but that's the general idea.

**Comment by jbarlow83** [comment]
Doesn't look that bad actually... I think this is all configuration.

Did you base the packaging scripts on Fedora's or this being done anew? Whatever Fedora does/did works.

Probably fixes for each log line below:

```
ERROR    ocrmypdf._exec.tesseract:tesseract.py:252 [tesseract] Error opening data file /usr/share/tesseract/tessdata/osd.traineddata
```

^ Need to install `tesseract-osd` (mandatory dependency).

```
  /root/.venv/lib64/python3.11/site-packages/pikepdf/_methods.py:266: UserWarning: pikepdf is missing some specialized decoders (probably JBIG2) so not all stream contents can be tested.
    self._decode_all_streams_and_discard()
```

^ Need to install `jbig2dec` (optional but recommended).

```
FAILED tests/test_helpers.py::TestFileIsWritable::test_chmod - AssertionError: assert not True
FAILED tests/test_hocrtransform.py::test_mono_image - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-root/pytest-2/popen-gw0/test_mono_image0/blank....
FAILED tests/test_main.py::test_pagesize_consistency[hocr] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ocrmypdf.io.wkuvfbmk/000001_ocr_hocr.hocr'
FAILED tests/test_pdfa.py::test_pdfa[1-3] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-root/pytest-2/popen-gw0/test_pdfa_1_3_0/out.pdf'
FAILED tests/test_pdfa.py::test_pdfa[2-3] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-root/pytest-2/popen-gw0/test_pdfa_2_3_0/out.pdf'
FAILED tests/test_pdfa.py::test_pdfa[3-3] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-root/pytest-2/popen-gw0/test_pdfa_3_3_0/out.pdf'
FAILED tests/test_main.py::test_input_file_not_readable - assert <ExitCode.ok: 0> == <ExitCode.input_file: 2>
```

^ Looks as if /tmp/pytest-of-root folder is not writable by the user running the test. You could also set the TMPDIR environment variable to a writable location for testing.


```
FAILED tests/test_optimize.py::test_jbig2_lossy[False] - ocrmypdf.exceptions.MissingDependencyError: Could not find program 'pngquant' on the PATH
FAILED tests/test_optimize.py::test_jbig2_lossy[True] - ocrmypdf.exceptions.MissingDependencyError: Could not find program 'pngquant' on the PATH
```

^ Need to install `pngquant` (required for test suite, optional but recommended for runtime).

```
FAILED tests/test_rotation.py::test_rotate_deskew_ocr_timeout - ocrmypdf.exceptions.SubprocessOutputError
```

^ Likely due to `tesseract-osd` not being installed.

**Comment by nemobis** [comment]
> Last OS error: No such file or directoryGPL Ghostscript 10.02.1: Unrecoverable error, exit code 1

I get this error in Fedora 41 with ocrmypdf 16.7.0 and gs 10.03.1, even installing from fedora repositories.
