### ISSUE TITLE
[Bug]:  Bunch of incomprehensible OCR content to delete

### ISSUE THREAD

**Issue by nicolas-75** [ocrmypdf/OCRmyPDF#1227]
### Describe the bug

A supplier sends me PDF files that all have the same problem. In fact, they're perfectly readable, I can double-click to select the text and copy it. However, when I paste the resulting file, I get a bunch of incomprehensible characters. For example: ,-++2),2 +23811319

I've tried several readers and still have the same problem, so I don't think the problem is with the reader.

The only solution I've found to have a correct OCR is to use option --force-ocr But under these conditions, file sizes become very large. From 0.6 MB, it can become more than 18 MB. On each file, that's a lot.

Is there an option for removing any OCR layer from an existing file, without turning it into an image?

### Steps to reproduce

```plain text
1. ocrmypdf -l fra --redo-ocr --output-type=pdf input.pdf output.pdf
2. open the PDF in any reader
3. no text can be found. and copying and pasting produces unusual characters

I put a file encrypted with jbarlow83 key
```

### Files

[RGDD.zip](https://github.com/ocrmypdf/OCRmyPDF/files/13819982/RGDD.zip)

### How did you download and install the software?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

14.0.1

**Comment by jbarlow83** [comment]
This usually happens when the PDF has a font but is missing/has corrupted version of an important resource, the font glyph number to Unicode mapping table, an internal data structure in the PDF. Some PDF viewers try to guess the mapping when this table is not present, leading to mojibake.

(`--redo-ocr` won't work here, because that feature attempts to distinguish OCR text from visible text, and you have visible text.)

You can try rewriting these using Ghostscript:
`gs  -sUseOCR=AsNeeded -sDEVICE=pdfwrite -o output.pdf input.pdf`

Doing so asks Ghostscript to apply OCR to the font itself and reconstruct the missing Unicode mapping. Some day I'll teach ocrmypdf to use that feature of Ghostscript when it makes sense to.

**Comment by nicolas-75** [comment]
That's don't change the result. Like others tools I used :cry:

**Comment by jbarlow83** [comment]
I tried several things and couldn't rescue it without force-ocr. 

(I make no accusations, but I almost wonder if the PDF was designed to defeat copy-paste accessibility for some reason. There's no glaring mistakes that would trip up a PDF viewer.)
