### ISSUE TITLE
[Feature]: Add support for docTR as alternate OCR backend?

### ISSUE THREAD

**Issue by victorhooi** [ocrmypdf/OCRmyPDF#1243]
### Describe the proposed feature

What do you think about adding support for [docTR](https://github.com/mindee/doctr) as a backend (as an alternative to Tesseract)?

Some people online report having decent success with it for OCR, and it seems to work well for my use-case (receipts), based on playing with the online demo.

**Comment by jbarlow83** [comment]
There are many new experimental OCR engines right now and no clear winners as far as I know. There is a plugin interface and example plugin for OCRmyPDF-EasyOCR, so you could write a plugin based on that. Because of this I'm not going to add any new backends myself, unless some compelling emerges. There are also significant complications to GPU renderers with containers, etc. so it makes sense for vanilla ocrmypdf to support Tesseract which runs everyone.

If an engine outputs hOCR it may not necessarily work with ocrmypdf because ocrmypdf's hocr renderer does not understand all of the hocr spec, just the subset that Tesseract generates.

I can answer questions or help with changes to core ocrmypdf if needed to support a plugin.

**Comment by jbarlow83** [comment]
I have to say OnnxTR does look pretty promising.

**Comment by felixdittrich92** [comment]
We added a notebook which uses OCRmyPDF and docTR's hOCR output to create PDF/A files:

https://colab.research.google.com/github/mindee/notebooks/blob/main/doctr/export_as_pdfa.ipynb

This works the same way with OnnxTR :)

**Comment by clefru** [comment]
I vibe-coded a plugin for docTR. Works okayish. The recognition quality isn't up to the level of Azure, so I doubt that will invest more time into that. But here it is, if somebody wants to play around it. https://github.com/clefru/ocrmypdf-doctr
