### ISSUE TITLE
Incorrect behavior of text color setting in hocrtransform

### ISSUE THREAD

**Issue by ep0p** [ocrmypdf/OCRmyPDF#1326]
The `canvas.do.fill_color(BLACK)` (line 340) command in the `hocrtransform` module is intended to set the text color to black. However, it incorrectly colors the background of the text box instead of the text itself. This behavior leads to visibility issues with the text, as the intended color setting does not apply correctly.

Steps to Reproduce:

1. Call the to_pdf method to create an pdf from a hocr file:
```
      hocr2 = HocrTransform(
          hocr_filename=(os.path.join(output_hocr_folder,"hocr.xml")),
          dpi=300
      )
      hocr.to_pdf(
          out_filename=output_pdf_path,
          invisible_text=False,
      )
```
2. Open the resulting PDF.
3. Observe that text boxes have a black background instead of black text: 
![Screenshot from 2024-06-07 16-37-29](https://github.com/ocrmypdf/OCRmyPDF/assets/168719294/4b2c4aaa-a7d3-4c1a-b345-33bf881eb9ff)

**Comment by jbarlow83** [comment]
You're trying to do something quite specific with a piece of the API but it's not quite to me why you're doing this.

OCRmyPDF uses the hocr to generate an invisible text layer (a PDF sized the same as the input page) that contains selectable text at the correct positions, and then combines this with the original page image. In combination, the text becomes selectable. It does not attempt to reconstruct the PDF by doing OCR and rendering using a font - that's complex and potentially data-destroying since the original image is not preserved so OCR errors become permanent. 
You would have to do what OCRmyPDF does and combine the invisible_text=True PDF with the page image, and render with invisible_text=True. The page image is how we get the characters.

The font OCRmyPDF uses is called GlyphlessFont. It defines just a single glyph (visual representations of characters), both empty, and then maps every Unicode character to the second glyph. (Fonts have a many to many relationship with Unicode characters; accented characters are often rendered as two or glyphs, and certain Unicode character bigrams will render as a single glyph for ligatures.) Read the [design notes here](https://github.com/tesseract-ocr/tesseract/blob/b0a10bbe1a5c3f55d79c4f00cb18d688726d5275/src/api/pdfrenderer.cpp#L50).
 
invisible_text=False is mostly a debug mode. There is some debug stuff where you are in a pure Latin alphabet you can use PDF default Helvetica and then you'd have a way to see the rendered text. See tests/test_canvas.py::test_text 

Some PDF viewers (you didn't say which you used) might not understand the GlyphlessFont. PDF viewers can be quite inconsistent.

**Comment by ep0p** [comment]
Yes you are right, i am indeed using the HocrTransform to recreate a simple pdf and not a pdf/a. I have used the previous version where you were building the pdf using  pdfgen and wanted to check the version with pikepdf.

Thank you for this explanation.
