### ISSUE TITLE
Docker build fails on Docker Hub

### ISSUE THREAD

**Issue by webphax** [ocrmypdf/OCRmyPDF#236]
Hey, anyone an idea why the automated build process at Ducker Hub fails since a couple of days? Since 2018-03-09T16:37:32.976Z the following error occurs: 
> Build failed: The command '/bin/sh -c . /appenv/bin/activate; pip install -r /application/test_requirements.txt' returned a non-zero code: 1

first build where the error occurred: https://hub.docker.com/r/jbarlow83/ocrmypdf/builds/btw7ecyuaducqi3pxow3yw9/

**Comment by jbarlow83** [comment]
Apparently it's time for me to move to Docker Cloud.

**Comment by jbarlow83** [comment]
Should be good now.

**Comment by webphax** [comment]
Hi @jbarlow83 , the build still fails (Unexpected error).

**Comment by jbarlow83** [comment]
The build on Docker Hub still shows a faillure. The solution seemed to the problem seemed to be to move to Docker Cloud which is the clunky replacement for Docker Hub. 

But if you pull the image you can see it's current:

```
$ docker pull jbarlow83/ocrmypdf
$ docker run --rm jbarlow83/ocrmypdf --version
5.7.0
```

**Comment by tobltobs** [comment]
Could you give a tip how I would pull the image from cloud instead of Hub. If I 
`docker pull jbarlow83/ocrmypdf
$ docker run --rm jbarlow83/ocrmypdf --version
6.1.2`

But running ocrmypdf results in an Error with a Debug Message that `PyMuPDF not installed`, which sounds like the requirement.txt wasn't installed.
