### ISSUE TITLE
Create an AppImage for ocrmypdf

### ISSUE THREAD

**Issue by jbarlow83** [ocrmypdf/OCRmyPDF#364]
I'd love to have an [AppImage](https://appimage.org/) but the process for creating one that bundles Python and many other programs besides is a bit intimidating - so I thought I'd reach to see if there anyone with experience in this can help out.

**Comment by FPille** [comment]
@jbarlow83 
I have created a [OCRmyPDF-AppImage github repository](https://github.com/FPille/OCRmyPDF-AppImage) that uses TRAVIS CI to build the AppImage.
I haven't created a PR, because I don't know how to extend your .travis.yml to include the AppImage build script properly.

The file size of the AppImage is 430 MB.
Python and OCRmyPDF including dependencies require about 110 MB.
tessdata (all languages) requires about 320 MB. 

Travis executes mainly two different tests:
- [appimagelint](https://github.com/TheAssassin/appimagelint): this test passes
- Your pytest tests where one test fails. Refer to the [issue](https://github.com/FPille/OCRmyPDF-AppImage/issues/1#issue-474215215) I created

This is my approach for an AppImage for OCRmyPDF. 
There are some things to improve:
- CLI: provide a _usage_ output that lists the embedded command line programs see[ AppRun.sh](https://github.com/FPille/OCRmyPDF-AppImage/blob/8cd87bd26f43dbc275982047606eda775adf9250/appimage/AppRun.sh#L3-L6)
- Add [Optional Resources and Features](https://docs.appimage.org/packaging-guide/optional/index.html#optional-resources-and-features)

**Comment by jbarlow83** [comment]
Thanks, this is wonderful. 

It looks as if `test_flate_to_jbig2` fails because the version pngquant used predates the ``--skip-if-larger`` parameter being added to that command in about 2016. Not sure why that would be the case but if necessary I can change it to not be dependent on that argument.

Is this effective a Ubuntu 14.04 "image"?

Is there a way to show the licenses? The image has a lot of licenses in it. (The easy thing to do is just display `debian/copyright`.)

I think the thing to do will be insert the AppImage .travis.yml as a separate build stage to run if everything else passes, because it needs to override the standard steps.

(I wrote this message shortly after yours but just realized I never submitted. Sorry for the delay.)

**Comment by FPille** [comment]
:smile: You're welcome! I use ocrmypdf for many years so it's time to give something back.
Thank you for your great work!

I have added a ppa to use a newer version of pngquant (2.5.0), but `test_flate_to_jbig2` still fails.

The image runs on Ubuntu 14.04 without the installation of additional packages, it has been built on "trusty" by travis and appimagelint doesn't complain (see below).  
![image](https://user-images.githubusercontent.com/50119297/62385229-c9db8d00-b554-11e9-9e23-697560d06e06.png)
I think we can call it a Ubuntu 14.04 image :wink: .

The AppRun.sh script can be extended to list all licences that are in the image and in a second step the license to be shown must be entered. This is a bit cumbersome with so many license files (primarily for the user). Does `debian/copyright` cover all licenses within this AppImage? Moreover, the image doesn't contain all files mentioned in `debian/copyright`. Anyway, I will extend the AppRun script by displaying license files and then there is better basis for discussion.

Once you have added the appimage build script to your .travis.yml I'll delete my repo.

**Comment by FPille** [comment]
The AppImage provides a simple user interface now. 
When run without parameters or with `--help` a usage output is shown. 

`--list-programs` shows the programs of the image that can be run when passed as first parameter.
`./OCRmyPDF-8.3.2-x86_64.AppImage ocrmypdf` or `./OCRmyPDF-8.3.2-x86_64.AppImage qpdf` ...

`--list-licenses` lists all copying, copyright and license files of the image including the path.
To display a single license file `--show-license` followed by the path to the license file must be entered:
`./OCRmyPDF-8.3.2-x86_64.AppImage --show-license usr/share/doc/ghostscript/copyright` shows the respective license file with less. Some license files are quite long so that less makes it easier to handle those files.
There is one license file for each tesseract language (161 overall). These don't differ so `--list-licenses` could show only one output for all languages (tessdata or tesseract-ocr-all) to get a clearer overview.

AppImage can be downloaded [here](https://github.com/FPille/OCRmyPDF-AppImage/releases/download/continuous/OCRmyPDF-8.3.2-x86_64.AppImage)

**Comment by jbarlow83** [comment]
I merged your work in a subtree into the main repo, such that it preserves your commit history and I can pull from your repo again as needed. Made a few changes here and there, mainly taking advantage of all ocrmypdf's files being present.

Do we have to compile Python? That seems unusual.

**Comment by FPille** [comment]
Thanks for merging! 

Good point! Compiling Python with each Travis build takes a lot of time unnecessarily and floods the job log. Another option could be to build a _pure Python3 AppImage_ a single time like [this one](https://github.com/niess/linuxdeploy-plugin-python/releases) The build script downloads this image and extracts it. Then we have an AppDir that contains Python. Next add/install OCRmyPDF and dependencies to the AppDir. Finally build the OCRmyPDF-AppImage without linuxdeploy-plugin-python. 
<pre><code>./linuxdeploy-x86_64.AppImage --appdir AppDir <del>--plugin python </del>\
    -d ocrmypdf.desktop -i ocrmypdf.png \
    --custom-apprun "$TRAVIS_BUILD_DIR"/misc/appimage/AppRun.sh --output appimage</pre></code>
I'll try to build the AppImage this way and report on the result. 

Regarding 14.04 image: The oldest still-supported Ubuntu LTS release is currently Ubuntu 16.04. I guess we should switch to xenial. Then it's easier to maintain the image.

Do you already know that the image is listed on [appimage.github.io](https://appimage.github.io/OCRmyPDF/)? It wasn't me. I discovered it by accident yesterday. I think they scan github for not yet listed AppImages and when they pass their tests these images are added. AppImage/appimage.github.io#1640

**Comment by shuvashish76** [comment]
Unofficial AppImage is available at https://github.com/pkgforge-dev/OCRmyPDF-AppImage by Package Forge devs.
