### ISSUE TITLE
Jbig2 dependency on windows

### ISSUE THREAD

**Issue by mortang2410** [ocrmypdf/OCRmyPDF#748]
On Windows, I would like to make ocrmypdf recognize the jbig2 executable (which I obtained from other sources) as a dependency.

How should I accomplish this? I have already made sure the PATH and PYTHONPATH variables lead to jbig2. Is there some other trick to make sure ocrmypdf "sees" the jbig2 executable?

**Comment by jbarlow83** [comment]
You need to run `--optimize 1` or higher (maybe 2? I forget) and you need a PDF that contains monochrome images that are not already jbig2. Try testing it on `tests/resources/ccitt.pdf`.

Check if ocrmypdf can find it like so:
```python
import ocrmypdf._exec.jbig2enc as jb
jb.available()
```

You should be able to type `jbig2` in the Command Prompt and Windows should find it rather than complaining file not found or whatever it says.

If you know of a precompiled jbig2 executable would you mind linking it? Perhaps it would be suitable to add to the download instructions for Windows.

**Comment by thethinker990** [comment]
https://soft.rubypdf.com/software/windows-version-jbig2-encoder-jbig2-exe

**Comment by jbarlow83** [comment]
Thanks - that is an older version of jbig2 but should still work. (I don't think I can recommend it though, because there's no transparency around how it was built.)

What result do you get from running the Python commands above?

**Comment by thethinker990** [comment]
It don't works. With windows cmd I find the exec and can return the version (as above) but with ocrmypdf I get still the warning/error type message.

Where do I have to put the files to get it properly work?

With chocolatey it says the package doesn't exists. I wanted to build it with this tutorial: https://github.com/agl/jbig2enc/blob/master/INSTALL
```
Download leptonica-1.68-win32-lib-include-dirs.zip from
http://leptonica.com/download.html and unpack it so 'include', 'lib' and
'jbig2enc' directories are at the same directory (or adjust include path
in VC++ project).

Download stdint.h for Microsoft Visual Studio (part of package
msinttypes-r26.zip from http://code.google.com/p/msinttypes/downloads/list)
and place it to 'include' directory.

Them open vs2008/jbig2enc.sln in Visual C++ 2008 and build solution.
```

**Comment by jbarlow83** [comment]
Chocolately doesn't have a package for everything. I'd love for someone to properly package ocrmypdf for Chocolately... ideally someone who is not me since I don't regularly use or develop for Windows.

What happens if open `cmd`, explicitly set PATH to include the path to jbig2.exe, and then run Python? Perhaps Python is not picking up the same environment variables that point to jbig2.exe?

**Comment by thethinker990** [comment]
I will try that on the weekend.

**Comment by anotatta** [comment]
Jbig2 0.29 binary for Windows 10,

https://github.com/anotatta/jbig2enc/releases/tag/0.29

**Comment by jbarlow83** [comment]
@anotatta Thanks. If you're willing to make a GitHub Action that produces and releases this binary I'd be happy to link to it and make it part of the documentation. Otherwise I'm hesitant to promote it since there's no transparency about how the binary was generated.

**Comment by anotatta** [comment]
@jbarlow83, Ideally that would not be me who is clueless about Github Action.

**Comment by PasaOpasen** [comment]
@anotatta this .exe file does not work without some .dll

If it worked in your machine, u have `liblep-5.dll`. Can u send this please?

**Comment by anotatta** [comment]
Try this repository https://github.com/manisandro/gImageReader
It should be in the bin directory.

**Comment by PasaOpasen** [comment]
@anotatta thank u, I tried, but there is only `libleptonica-5.dll` what is not exactly `liblept-5.dll` and cannot replace it

**Comment by anotatta** [comment]
Strange, my latest portable zip version of gImageReader contains  liblept-5.dll but not libleptonica-5.dll.
Anyway dumpbin indicates the following dependencies: liblept-5.dll, KERNEL32.dll, msvcrt.dll, WS2_32.dll,  libgcc_s_seh-1.dll, libstdc++-6.dll
The last two you can get from Perl Strawberry distribution.

**Comment by PasaOpasen** [comment]
@anotatta I found last 2 before, can u give me archive with `liblept-5.dll` or this portable gImageReader ?

**Comment by anotatta** [comment]
gImageReader portable or Tesseract for windows should also have it.  Good luck.

**Comment by PasaOpasen** [comment]
Finally I found it here https://github.com/manisandro/gImageReader/releases/download/v3.0/gImageReader_3.0_qt5_x86_64.exe

**Comment by cldjr1** [comment]
I'm still interested in getting this to work on Windows. Has anyone figured this out?

**Comment by PasaOpasen** [comment]
@cldjr1 I found some necessary dll and put them here

https://github.com/PasaOpasen/dll_exe_collection

Just download and add the location to PATH

**Comment by user1823** [comment]
The download from https://sourceforge.net/projects/jbig2enc/ seems to work well. Just download the zip file, extract it and add the folder to your system PATH.

**Comment by 459737087** [comment]
When I added this folder, It reported 0xc000007b

**Comment by user1823** [comment]
I am just a normal user and I can't help you with the error. Sorry.

**Comment by sjain882** [comment]
> The download from https://sourceforge.net/projects/jbig2enc/ seems to work well. Just download the zip file, extract it and add the folder to your system PATH.

I did as you said but the error persists... did you mean add it to WSL / Ubuntu path somehow, instead of Windows path? Could you elaborate on how exactly you did that please. Thanks.

I added `C:\Program Files\jbig2enc` to my Windows PATH and restarted all cmd / bash / Ubuntu windows but it didn't help. I just extracted the archive inside that folder

**Comment by jbarlow83** [comment]
As far as I know both ocrmypdf and jbig2enc need to be in native Windows or Linux. I wouldn't count on crossing the boundaries to work.

**Comment by user1823** [comment]
> did you mean add it to WSL / Ubuntu path somehow

I meant adding it to the Windows path and using it within Windows. I have no idea how WSL works.

> I added C:\Program Files\jbig2enc to my Windows PATH
> I just extracted the archive inside that folder

Make sure that jbig2.exe is directly under the C:\Program Files\jbig2enc and not in any subfolder.

<img width=500 src="https://github.com/user-attachments/assets/91aa517f-08bb-4b8c-8faf-b53fe7e0144b">

Did you try running `jbig2 --version` in CMD? If you have set the path correctly, it should give `jbig2enc 0.29` as the output instead of returning `'jbig2' is not recognized as an internal or external command, operable program or batch file.` as the error.

**Comment by sjain882** [comment]
> I meant adding it to the Windows path and using it within Windows. I have no idea how WSL works.

Apologies. Seeing WSL as the only listed option for Windows in the Readme made me assume the Native instructions weren't to be followed. I set it up natively and all is well now. Thanks
