### ISSUE TITLE
NAS Synology > Docker > is not a writable file

### ISSUE THREAD

**Issue by Ludek007** [ocrmypdf/OCRmyPDF#900]
Hi,
I can't figure out where the problem is

*********************
drwxrwxrwx+ 1 root       root        26 Jan 19 20:14 docker

user@DS_backup:/volume1$ docker run --rm -i ocrmypdf /volume1/docker/001.pdf /volume1/docker/out001.pdf
OutputFileAccessError: Output file location (/volume1/docker/out001.pdf) is not a writable file.

root@DS_backup:~# docker run --rm -i ocrmypdf /volume1/docker/001.pdf /volume1/docker/out001.pdf
OutputFileAccessError: Output file location (/volume1/docker/out001.pdf) is not a writable file.

Docker version 20.10.3, build b455053
Ocrmypdf version 13.2.0.post7+g2d0ac470.d20220116

***********************
Thank you

**Comment by jbarlow83** [comment]
I recommend streaming the file in and out as discussed in the documentation, e.g. `docker run --rm -i ocrmypdf - -  </volume1/docker/001.pdf >/volume1/docker/out001.pdf`

Setting up a docker container so that it can access host files is difficult to get right and not ideal from a security perspective.

**Comment by Ludek007** [comment]
Perfect, thank you
