### ISSUE TITLE
Scanning Comic books

### ISSUE THREAD

**Issue by yosamshiyam** [ocrmypdf/OCRmyPDF#925]
**What's the problem?**

A couple days ago, I tried to run OCRmyPDF on a few comic books I had in PDF format, specfically, _Tintin_ and _Asterix_.  Unfortunately, despite OCRmyPDF stating there were no errors or problems in the conversion, ocrmypdf recognized only about a quarter of the pages (despite stating it recognized everything).   

I tried ocrmypdf with several other comic books but all of them seemed to have the same issue.  I suspect it's a matter of tesseract having difficulty seeing inside comic book text bubbles and the often indefinite placement (by that I mean, that text doesn't really follow any line-by-line pattern) words on the page.  

I tried running the PDF files through _Abbyy_, another propietary OCR engine I have access to, but it had the same issues.  It said it recognized the text, but didn't, not really.  So...I'm guessing the technology isn't there yet to scan complex text documents like comic books? Regardless, I might be mistaken so I thought to put this out there in the event someone can help.  

**Steps to reproduce the behavior.**
Take any generic comic book and run it through OCRmyPDF. Single pages of Tintin or Asterix are easy to find, if you are worried about copyright issues.You'll see what I mean. 

**What did you expected to happen?**
Honestly, I expected it to work.  I mean comic books have much less text per page compared to other documents.  But I imagine as the captions and writing in bubbles are typically in a kind of handwriting that OCR is difficult as a result.  

Still, the fact that most comic books are written all in caps for me equated to OCR recognition software having an easier time deciphering things as it does have to worry about letters written in small case.  But I could be mistaken as I don't have much experience with this type of software.

**If applicable, add screenshots to help explain your problem.
**
It's not really applicable because OCRmyPDF doesn't recognize any problems; it just doesn't seem to OCR the page and seems to think it a picture (which isn't far from the truth as it's a comic book, after all).

 **- OS: MacOS 12.2.1
 - Python version: 3.9
 - OCRmyPDF version:** the latest available on homebrew (sorry, I'm currently on a tablet away from my computer and can't access the terminal from here).  But as I recently installed it (like last week), I'm guessing it's the latest gen.

**How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?**

I installed OCRmyPDF via the _Homebrew_ package manager.

**Additional context**
I'm thinking of converting the pdf file into a set of image files and then running ocrmypdf but my suspicion is that that won't change things much as the files orignally aren't OCR recognized.  My apologies for not being able to attach the files due to copyright infringement.  But really, Tintin and Asterix are both readily available on the net, so it wouldn't be hard to find a page in either comic book series, run it through OCRmyPDF and you'll see what I mean.

**Comment by jbarlow83** [comment]
This is really a Tesseract issue because our main job is to 1) give the best information we can to Tesseract, 2) make the best PDF based on what Tesseract found. It still looks after the OCR bit in the middle and likely needs help for comic books.

Maps cause similar problems for Tesseract. Natural landforms can look letter-like. Words can be anywhere with wavy baselines. Graphic objects are mixed with.

You may get better results using Tesseract 5.x and using the `--tesseract-thresholding` argument which lets you pick among some options which may perform for some kinds of images.

Tesseract may also be under-trained on comic book fonts and vocabulary. There are ways to get it to produce intermediate images and visualizations that let you see what it "sees", documented on the Tesseract side of things.

Another option you could explore is writing a plugin to replace Tesseract with another OCR engine of your choosing.

So with those explanation I'll be closing this since I don't expect there's much opportunity for me to make ocrmypdf better at this. The issues need to be fixed in OCR engines, if someone can be motivated to do so.
