### ISSUE TITLE
Issue with OCR not completing

### ISSUE THREAD

**Issue by Eksx** [ocrmypdf/OCRmyPDF#941]
**Describe the bug**
What's the problem?

I am running ocrmypdf inside a docker container on AWS batch. When attempting to run pdf conversions over ~150 pdf pages the ocr process fails. The logging is inadequate to figure out the source of the issue. Below I attached a screenshot that shows the logging.

**Expected behavior**
What did you expected to happen?
The pdf should output as ocr but instead the process seems to fail mid ocr.

**Screenshots**
<img width="1150" alt="Screen Shot 2022-04-03 at 8 25 03 PM" src="https://user-images.githubusercontent.com/3720245/161485941-70694ca2-84c3-491e-a509-f8008b9481c6.png">

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3
 - OCRmyPDF version: 13.4.1

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
Installed inside docker container using apt install.

**Comment by jbarlow83** [comment]
Can ocrmypdf process the same file on a local machine? How long does it take? Did you try running it on a larger EC2 instance to see if it's a CPU/space/memory limit? On a low end box ~10 pages/minute isn't that far off and running out of memory on e.g. lambda instances is a distinct possibility. You need to allow several MB per page for temporary files.

**Comment by Eksx** [comment]
@jbarlow83 Thank you for your response. Running the pdf locally does work do i think you are definitely correct about it being an issue with EC2. Apologies if this is not the correct place to ask this but, do you have a recommended box to use in order to be able to ocr pdfs that could be up to 1000 pages and pretty heavy on images? Currently i was using using boxes with at least 2cpu and 16gb of memory. I upgraded the disk driver to be 100gb. But i am wondering if docker is not using the correct drive in order to save the temp files. Any feedback you can provide is greatly appreciated!

**Comment by jbarlow83** [comment]
I'd probably go for something like 8 or 16 CPU from the compute family. A spot request of "whatever is cheap, Mr. Bezos" minus the lowest end boxes should work too. You want at least AVX and AVX2, ideally AVX-512. Without those floating point instruction sets, OCR can run really slow - minutes per page.  You also need HVM not PV instances since the latter don't have floating point even if the hardware does.

The rest of your specs are probably okay. I'd personally pass on docker for OCR jobs because I think it adds complexity without benefit, but I can also think of applications where you'd want it.

I haven't tried the AWS ARMs so can't comment, but if they don't have NEON they will perform poorly.

**Comment by Eksx** [comment]
@jbarlow83 Your advice to use larger Compute instances has worked great. Thank you for helping me out with this!
