### ISSUE TITLE
Creating txt file without an output pdf. Examples missing for correct syntax.

### ISSUE THREAD

**Issue by gevezex** [ocrmypdf/OCRmyPDF#942]
**Describe the bug**
Text file only output seems not working

**To Reproduce**
```
import ocrmypdf
filename = 'random.pdf'


if __name__ == '__main__':
    ocrmypdf.ocr(input_file=filename, output_file='-', output_type=None, language='nld', sidecar='a.txt', force_ocr=True)
```
   

**Expected behavior**
create output file 'a.txt' with only the ocr-ed text

**exception**
`ocrmypdf.exceptions.BadArgsError: Output was set to stdout '-' but it looks like stdout is connected to a terminal.  Please redirect stdout to a file.`

Does anyone know what the proper arguments are for creating the sidecar file and not creating a new pdf (no pdf output file).

With the command line i can do this without error with  the following command:
ocrmypdf --force-ocr --output-type=none --sidecar a.txt random.pdf - > /dev/null

What is the equivalent doing this in a python script as above?

**Comment by jbarlow83** [comment]
On non-Windows you can set `output_file='/dev/null'`

**Comment by z0xyz** [comment]
It seems that outputting to a file or standard output of the terminal, can be be also suppressed by piping another random command i.e. `ocrmypdf file.pdf - --output-type none --sidecar file.txt | ls`

**Comment by batterseapower** [comment]
In case anyone else found this via google: if you want to call `ocrmypdf.ocr(input_file, output_file, output_type='none')` from a Python script the only acceptable value for `output_file` is `os.devnull`. If you use `-` then `ocrmypdf` blows up because `-` is a terminal (IMHO this is a bug - this check should not be done if `output_type='none'`). If you use any non-`-` file then `ocrmypdf` blows up because if `output_type='none` then it doesn't like you specifying an explicit filename.
